<div>
<img src=https://www.institutedata.com/wp-content/uploads/2019/10/iod_h_tp_primary_c.svg width="300">
</div>

# Linear Algebra - Part 1

In [3]:
import numpy as np

### 1. Compute the scaler product of two vectors

In mathematics, the dot product or scalar product is an algebraic operation that takes two equal-length sequences of numbers (usually coordinate vectors) and returns a single number. 

We can calculate it this way:

        a · b = ax × bx + ay × by
        
Hint: [Dot Product](https://www.mathsisfun.com/algebra/vectors-dot-product.html)

```
# Expected Output:
0
```

In [4]:
a = [-12, 16]
b = [12, 9]

In [5]:
#ANSWER (1 line)
np.dot(a,b)

0

### 2. Compute the cross product of two vectors

> When a and b start at the origin point (0,0,0), the Cross Product will end at:

        cx = aybz − azby
        cy = azbx − axbz
        cz = axby − aybx
        
Hint: [Cross Product](https://www.mathsisfun.com/algebra/vectors-cross-product.html)
```
# Expected Output:
array([[-3,  6, -3],
       [ 3, -6,  3]])
```

In [6]:
x = np.array([[1,2,3], [4,5,6]])
y = np.array([[4,5,6], [1,2,3]])

In [7]:
#ANSWER (1 line)
np.cross(x,y)

array([[-3,  6, -3],
       [ 3, -6,  3]])

### 3. Compute the Hademard product (entry-wise multiplication) of two vectors.

> In mathematics, the Hadamard product (also known as the Schur product[1] or the entrywise product[2]:ch. 5) is a binary operation that takes two matrices of the same dimensions and produces another matrix of the same dimension as the operands where each element i, j is the product of elements i, j of the original two matrices. It should not be confused with the more common matrix product. It is attributed to, and named after, either French mathematician Jacques Hadamard or German mathematician Issai Schur. [Wiki](https://en.wikipedia.org/wiki/Hadamard_product_(matrices))

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/4eb9bb54b2820fb3583901ec05bc4b474b6d90bc)
```
# Expected Output:
array([[ 5, 12],
       [21, 32]])
```

In [8]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [9]:
#ANSWER (1 line)
np.multiply(a,b)

array([[ 5, 12],
       [21, 32]])

### 4. Compute the sum of two matrices.

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/0fb7845af355c550d44020e52699069c044126a9)
```
# Expected Output:
[17, 15, 4]
[10, 12, 9]
[11, 13, 18]
```

In [115]:
# Program to add two matrices using nested loop

X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

Y = [[5,8,1],
    [6,7,3],
    [4,5,9]]

result = [[0,0,0],
         [0,0,0],
         [0,0,0]]

In [116]:
#ANSWER (~3 lines)
# Row Iteration
for i1 in range(len(X)):
    #Columns iteration
    for i2 in range(len(X[0])):
        print("X[", i1 ,"][", i2,"]")
        print( X[i1][i2])
        print("Y[", i1 ,"][", i2,"]")
        print(Y[i1][i2])
        result[i1][i2] = X[i1][i2] + Y[i1][i2]
        print("sum(+) result: ", result[i1][i2])
        print("End of Calculation \n")
        
for r in result:
    print(r)

X[ 0 ][ 0 ]
12
Y[ 0 ][ 0 ]
5
sum(+) result:  17
End of Calculation 

X[ 0 ][ 1 ]
7
Y[ 0 ][ 1 ]
8
sum(+) result:  15
End of Calculation 

X[ 0 ][ 2 ]
3
Y[ 0 ][ 2 ]
1
sum(+) result:  4
End of Calculation 

X[ 1 ][ 0 ]
4
Y[ 1 ][ 0 ]
6
sum(+) result:  10
End of Calculation 

X[ 1 ][ 1 ]
5
Y[ 1 ][ 1 ]
7
sum(+) result:  12
End of Calculation 

X[ 1 ][ 2 ]
6
Y[ 1 ][ 2 ]
3
sum(+) result:  9
End of Calculation 

X[ 2 ][ 0 ]
7
Y[ 2 ][ 0 ]
4
sum(+) result:  11
End of Calculation 

X[ 2 ][ 1 ]
8
Y[ 2 ][ 1 ]
5
sum(+) result:  13
End of Calculation 

X[ 2 ][ 2 ]
9
Y[ 2 ][ 2 ]
9
sum(+) result:  18
End of Calculation 

[17, 15, 4]
[10, 12, 9]
[11, 13, 18]


### 5. Compute the product of two matrices.

![](https://upload.wikimedia.org/wikipedia/commons/e/eb/Matrix_multiplication_diagram_2.svg)
```
# Expected Output:
[114, 160, 60, 27]
[74, 97, 73, 14]
[119, 157, 112, 23]
```

In [125]:
# Program to multiply two matrices using nested loops

# 3x3 matrix
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

# 3x4 matrix
Y = [[5,8,1,2],
    [6,7,3,0],
    [4,5,9,1]]

# result is 3x4
result = [[0,0,0,0],
         [0,0,0,0],
         [0,0,0,0]]

In [126]:
#ANSWER (~3 lines)

print("X Row Length ", len(X))
print("Y column length ", len(Y[0]))
print("Y Rows length" ,len(Y))

# X Row Iteration
for i in range(len(X)):
    # Y Columns Iteration
    for j in range(len(Y[0])):
        # Y Rows Iteration
        for k in range(len(Y)):
            print("X[", i ,"]","[",k,"]")
            print( X[i][k] )
            print("Y[", k ,"]","[",j,"]")
            print( Y[k][j])
            print(X[i][k],"*",Y[k][j] ,"=", X[i][k] * Y[k][j])
            
            result[i][j] += X[i][k] * Y[k][j]
            
        print(result[i][j])
        print("End of Calculation \n")    
for r in result:
    print(r)
            


X Row Length  3
Y column length  4
Y Rows length 3
X[ 0 ] [ 0 ]
12
Y[ 0 ] [ 0 ]
5
12 * 5 = 60
X[ 0 ] [ 1 ]
7
Y[ 1 ] [ 0 ]
6
7 * 6 = 42
X[ 0 ] [ 2 ]
3
Y[ 2 ] [ 0 ]
4
3 * 4 = 12
114
End of Calculation 

X[ 0 ] [ 0 ]
12
Y[ 0 ] [ 1 ]
8
12 * 8 = 96
X[ 0 ] [ 1 ]
7
Y[ 1 ] [ 1 ]
7
7 * 7 = 49
X[ 0 ] [ 2 ]
3
Y[ 2 ] [ 1 ]
5
3 * 5 = 15
160
End of Calculation 

X[ 0 ] [ 0 ]
12
Y[ 0 ] [ 2 ]
1
12 * 1 = 12
X[ 0 ] [ 1 ]
7
Y[ 1 ] [ 2 ]
3
7 * 3 = 21
X[ 0 ] [ 2 ]
3
Y[ 2 ] [ 2 ]
9
3 * 9 = 27
60
End of Calculation 

X[ 0 ] [ 0 ]
12
Y[ 0 ] [ 3 ]
2
12 * 2 = 24
X[ 0 ] [ 1 ]
7
Y[ 1 ] [ 3 ]
0
7 * 0 = 0
X[ 0 ] [ 2 ]
3
Y[ 2 ] [ 3 ]
1
3 * 1 = 3
27
End of Calculation 

X[ 1 ] [ 0 ]
4
Y[ 0 ] [ 0 ]
5
4 * 5 = 20
X[ 1 ] [ 1 ]
5
Y[ 1 ] [ 0 ]
6
5 * 6 = 30
X[ 1 ] [ 2 ]
6
Y[ 2 ] [ 0 ]
4
6 * 4 = 24
74
End of Calculation 

X[ 1 ] [ 0 ]
4
Y[ 0 ] [ 1 ]
8
4 * 8 = 32
X[ 1 ] [ 1 ]
5
Y[ 1 ] [ 1 ]
7
5 * 7 = 35
X[ 1 ] [ 2 ]
6
Y[ 2 ] [ 1 ]
5
6 * 5 = 30
97
End of Calculation 

X[ 1 ] [ 0 ]
4
Y[ 0 ] [ 2 ]
1
4 * 1 = 4
X[ 1 ] [ 1 ]
5
Y[ 1

### 6. Compute the determinant of an n x n matrix.

![](https://integratedmlai.com/wp-content/uploads/2018/12/Matrix_Det_2x2.png)

Hint: [Find the Determinant of a Matrix with Pure Python without Numpy or Scipy](https://integratedmlai.com/find-the-determinant-of-a-matrix-with-pure-python-without-numpy-or-scipy/)

Hint: Use 
> np.linalg.det
```
# Expected Output:
17.999999999999996
```

In [135]:
matrix = [[-2,2,-3],[-1,1,3],[2,0,-1]]

In [137]:
#ANSWER (1 line)
print("Determinant of matrix is",np.linalg.det(matrix))

Determinant of matrix is 17.999999999999996


### 7. Compute the inverse of an n x n matrix.

For a 3×3 matrix

![](http://mathworld.wolfram.com/images/equations/MatrixInverse/NumberedEquation3.gif)

the matrix inverse is

![](http://mathworld.wolfram.com/images/equations/MatrixInverse/NumberedEquation4.gif)

Hint: Use 
> from numpy.linalg import inv
```
# Expected Output:
array([[-2. ,  1. ],
       [ 1.5, -0.5]])
```

In [129]:
a = np.array([[1., 2.], [3., 4.]])

In [138]:
#ANSWER (~2 lines)
print("Irverse of a array is ",np.linalg.inv(a))

Irverse of a array is  [[-2.   1. ]
 [ 1.5 -0.5]]




---



---



> > > > > > > > > © 2021 Institute of Data


---



---



